/**
 * Sidebar navigation. UI-agnostic: each LayoutSider maps `iconName` to its own
 * icon library. Generated by create-icore from a base (dashboard + profile) plus
 * the chosen features' contributions (e.g. notes when example=notes).
 */
export interface NavItem {
  to: string;
  labelKey: string;
  iconName: 'dashboard' | 'notes' | 'profile';
  exact?: boolean;
}

export const NAV_CONFIG: NavItem[] = [
  { to: '/dashboard', labelKey: 'nav.dashboard', iconName: 'dashboard', exact: true },
  { to: '/notes', labelKey: 'nav.notes', iconName: 'notes' },
  { to: '/profile', labelKey: 'nav.profile', iconName: 'profile' },
];
