/** Microservices the gateway proxies. Generated by create-icore. */
export const GATEWAY_SERVICES = [
  { name: 'auth', prefix: 'AUTH' },
  { name: 'upload', prefix: 'UPLOAD' },
  { name: 'notes', prefix: 'NOTES' },
  { name: 'payment', prefix: 'PAYMENT' },
];
