import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { CreateIcoreOptions } from '../lib/options.js';
import { MANIFEST } from './index.js';

const NAV_CONFIG_FILE = 'apps/client/src/nav.config.ts';

interface NavEntry {
  to: string;
  labelKey: string;
  iconName: string;
  exact?: boolean;
}

const BASE_NAV: NavEntry[] = [
  { to: '/dashboard', labelKey: 'nav.dashboard', iconName: 'dashboard', exact: true },
];
const PROFILE_NAV: NavEntry = { to: '/profile', labelKey: 'nav.profile', iconName: 'profile' };

function renderEntry(n: NavEntry): string {
  const parts = [`to: '${n.to}'`, `labelKey: '${n.labelKey}'`, `iconName: '${n.iconName}'`];
  if (n.exact) parts.push('exact: true');
  return `  { ${parts.join(', ')} },`;
}

/** Generate apps/client/src/nav.config.ts: dashboard + chosen-feature nav + profile. */
export async function writeNavConfig(targetDir: string, opts: CreateIcoreOptions): Promise<void> {
  const entries: NavEntry[] = [...BASE_NAV];
  const notesNav = MANIFEST.feature.notes.clientNav;
  if (opts.example === 'notes' && notesNav) {
    entries.push({
      to: notesNav.route,
      labelKey: notesNav.labelKey,
      iconName: notesNav.iconName,
      exact: notesNav.exact,
    });
  }
  entries.push(PROFILE_NAV);

  const content =
    `/**\n` +
    ` * Sidebar navigation. UI-agnostic: each LayoutSider maps \`iconName\` to its own\n` +
    ` * icon library. Generated by create-icore.\n` +
    ` */\n` +
    `export interface NavItem {\n` +
    `  to: string;\n` +
    `  labelKey: string;\n` +
    `  iconName: 'dashboard' | 'notes' | 'profile';\n` +
    `  exact?: boolean;\n` +
    `}\n\n` +
    `export const NAV_CONFIG: NavItem[] = [\n` +
    entries.map(renderEntry).join('\n') +
    `\n];\n`;
  await writeFile(join(targetDir, NAV_CONFIG_FILE), content);
}
