import { readFile, writeFile, rm, rmdir, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import type { CreateIcoreOptions } from '../lib/options.js';
import type { Unit } from './types.js';
import { MANIFEST } from './index.js';
import { stripJsonKeys, stripTsconfigKeys } from './wire-provider.js';
import { stripGatewayTransport } from '../lib/scaffold-env.js';

const FEATURES_MODULE = 'apps/api/src/app/features.module.ts';
const GATEWAY_SERVICES = 'apps/api/src/app/gateway-services.ts';
const API_PKG = 'apps/api/package.json';

type FeatureKey = 'notes' | 'payment' | 'jobs';

const FEATURES = MANIFEST.feature as Record<FeatureKey, Unit>;

/** Which features are selected, from the options. */
function selectedFeatures(opts: CreateIcoreOptions): FeatureKey[] {
  const out: FeatureKey[] = [];
  if (opts.example === 'notes') out.push('notes');
  if (opts.payment !== 'none') out.push('payment');
  if (opts.jobs !== 'none') out.push('jobs');
  return out;
}

/** features.module.ts (gateway imports) + gateway-services.ts (transport services). */
export async function writeFeaturesWiring(
  targetDir: string,
  opts: CreateIcoreOptions,
): Promise<void> {
  const chosen = selectedFeatures(opts);

  // features.module.ts — import + @Module of chosen gateway feature modules.
  const mods = chosen
    .map((k) => FEATURES[k].gatewayModule)
    .filter((m): m is NonNullable<typeof m> => !!m);
  const imports = mods.map((m) => `import { ${m.symbol} } from '${m.importFrom}';`).join('\n');
  const symbols = mods.map((m) => m.symbol).join(', ');
  const featuresModule =
    `import { Module } from '@nestjs/common';\n` +
    (imports ? imports + '\n' : '') +
    `\n@Module({\n  imports: [${symbols}],\n})\nexport class FeaturesModule {}\n`;
  await writeFile(join(targetDir, FEATURES_MODULE), featuresModule);

  // gateway-services.ts — auth (unless none) + upload (unless none) + chosen feature services.
  const services: { name: string; prefix: string }[] = [];
  if (opts.authProvider !== 'none') services.push({ name: 'auth', prefix: 'AUTH' });
  if (opts.upload !== 'none') services.push({ name: 'upload', prefix: 'UPLOAD' });
  for (const k of chosen) {
    const svc = FEATURES[k].gatewayService;
    if (svc) services.push(svc);
  }
  const entries = services.map((s) => `  { name: '${s.name}', prefix: '${s.prefix}' },`).join('\n');
  const gatewayServices =
    `/** Microservices the gateway proxies. Generated by create-icore. */\n` +
    `export const GATEWAY_SERVICES = [\n${entries}\n];\n`;
  await writeFile(join(targetDir, GATEWAY_SERVICES), gatewayServices);
}

async function stripJobsDockerCompose(targetDir: string): Promise<void> {
  const composePath = join(targetDir, 'docker-compose.yml');
  try {
    const compose = await readFile(composePath, 'utf8');
    const next = compose
      .replace(/\n {2}jobs:[\s\S]+?(?=\n {2}\w+:|\nnetworks:)/m, '\n')
      .replace(/\n {6}jobs:\n {8}condition: service_started/g, '')
      .replace(/\n {6}JOBS_REDIS_URL:[^\n]*/g, '');
    await writeFile(composePath, next);
  } catch {
    // ignore
  }
}

/** Remove every NOT-selected feature: its dirs, gateway deps + tsconfig aliases,
 *  its gateway .env transport block, and (jobs) its docker-compose service. The
 *  gateway app.module / main.ts are NOT touched — they consume the generated
 *  features.module.ts / gateway-services.ts. */
export async function cleanupUnusedFeatures(
  targetDir: string,
  opts: CreateIcoreOptions,
): Promise<void> {
  const chosen = new Set(selectedFeatures(opts));
  for (const key of ['notes', 'payment', 'jobs'] as FeatureKey[]) {
    if (chosen.has(key)) continue;
    const unit = FEATURES[key];
    for (const dir of unit.libDirs)
      await rm(join(targetDir, dir), { recursive: true, force: true });
    const dropKeys = new Set([...Object.keys(unit.tsPaths), ...Object.keys(unit.deps)]);
    await stripJsonKeys(join(targetDir, API_PKG), (k) => dropKeys.has(k));
    await stripTsconfigKeys(targetDir, Object.keys(unit.tsPaths));
    if (unit.gatewayService) await stripGatewayTransport(targetDir, unit.gatewayService.prefix);
    if (unit.dockerService === 'jobs') await stripJobsDockerCompose(targetDir);
    if (key === 'jobs') {
      // jobs.ts in libs/shared is only used by BullMQ — dead when jobs=none
      try {
        await unlink(join(targetDir, 'libs/shared/src/jobs.ts'));
      } catch {
        /* ignore */
      }
      const sharedIdx = join(targetDir, 'libs/shared/src/index.ts');
      try {
        const src = await readFile(sharedIdx, 'utf8');
        await writeFile(sharedIdx, src.replace(/^export \* from '\.\/jobs';\n/m, ''));
      } catch {
        /* ignore */
      }
    }
  }
  // Remove queries dir if emptied by feature removal (no-op when files remain)
  try {
    await rmdir(join(targetDir, 'apps/client/src/queries'));
  } catch {
    // ignore — not empty or doesn't exist
  }
}
